# https://numtide.github.io/devshell
[[commands]]
package = "nodejs"
name = "node"
help = "NodeJS"

[[commands]]
package = "nodePackages.pnpm"
name = "pnpm"
help = "NodeJS pnpm"

[[commands]]
package = "yt-dlp"
name = "yt-dlp"
help = "youtube dl"

[[commands]]
package = "ffmpeg"
name = "ffmpeg"
help = "ffmpeg and ffprobe"

[[commands]]
package = "sqlite"
name = "sqlite3"
help = "sqlite"

[[commands]]
package = "qmk"
name = "QMK CLI"
help = "qmk"
